### ISSUE TITLE
运行question_bot.py报错请问是哪里出问题了，安装了langchain-community依然报错

### ISSUE THREAD

**Issue by ATM006** [PaddlePaddle/ERNIE-SDK#326]
E:\jupyter\ERNIE-SDK\py311\Scripts\python.exe E:\jupyter\ERNIE-SDK\erniebot-agent\applications\eb-agent-qa-bot\question_bot.py --init=True --access-token xxxxxxxxxxxxxxxxxxxxxxxxxxxx 
  0%|          | 0/8 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\erniebot\auth.py", line 85, in upsert_auth_token
    auth_token = token_requestor()
                 ^^^^^^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\erniebot\auth.py", line 172, in _request_auth_token
    raise RuntimeError("Invalid API key or secret key")
RuntimeError: Invalid API key or secret key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\jupyter\ERNIE-SDK\erniebot-agent\applications\eb-agent-qa-bot\question_bot.py", line 99, in <module>
    agent = load_agent()
            ^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\erniebot-agent\applications\eb-agent-qa-bot\question_bot.py", line 67, in load_agent
    init_db(faiss_name, faiss_name_module, embeddings)
  File "E:\jupyter\ERNIE-SDK\erniebot-agent\applications\eb-agent-qa-bot\init_vector_db.py", line 93, in init_db
    content_doc = load_md_files_to_doc(md_file_path, chunk_size, chunk_overlap)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\erniebot-agent\applications\eb-agent-qa-bot\init_vector_db.py", line 75, in load_md_files_to_doc
    splits[i].page_content = get_summary(splits[i].page_content)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\erniebot-agent\applications\eb-agent-qa-bot\init_vector_db.py", line 24, in get_summary
    summary = erniebot.ChatCompletion.create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\erniebot\resources\chat_completion.py", line 261, in create
    resp = resource.create_resource(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\erniebot\resources\abc\creatable.py", line 67, in create_resource
    resp = self.request(
           ^^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\erniebot\resources\resource.py", line 144, in request
    for attempt in retrying:
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\tenacity\__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\ThinkPad\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ThinkPad\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\erniebot\resources\resource.py", line 146, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\erniebot\resources\resource.py", line 340, in _request
    resp = self._backend.request(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\erniebot\backends\bce.py", line 71, in request
    access_token = self._auth_manager.get_auth_token()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\erniebot\auth.py", line 113, in get_auth_token
    self._token = self._init_auth_token()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\erniebot\auth.py", line 137, in _init_auth_token
    token = self._update_cache(init=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\erniebot\auth.py", line 144, in _update_cache
    token, upserted = self._cache.upsert_auth_token(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\jupyter\ERNIE-SDK\py311\Lib\site-packages\erniebot\auth.py", line 87, in upsert_auth_token
    raise errors.TokenUpdateFailedError from e
erniebot.errors.TokenUpdateFailedError

**Comment by w5688414** [comment]
请问您的erniebot-agent和erniebot的版本是多少？

**Comment by Southpika** [comment]
您好 好像是没有输入正确的access-token～， 可以在个人中心的[访问令牌页面](https://aistudio.baidu.com/usercenter/token)获取用户凭证access token。

**Comment by JRYan888** [comment]
遇到了一样的问题，请问解决了吗

**Comment by JRYan888** [comment]
> 您好 好像是没有输入正确的access-token～， 可以在个人中心的[访问令牌页面](https://aistudio.baidu.com/usercenter/token)获取用户凭证access token。

我就是按照aistudio填写的，但还是会报错

**Comment by JRYan888** [comment]
> 请问您的erniebot-agent和erniebot的版本是多少？

我也遇到了一样的报错，版本号：
erniebot =0.0.0.dev0
erniebot-agent =0.0.0.dev0
